---
driver:
  name: digitalocean

provisioner:
  name: chef_zero

platforms:
  - name: centos-6-5-x64
    driver_config:
      size: 2GB
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
      ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>


suites:
  - name: default
    run_list:
      - recipe[boxed-rails::default]
    attributes:
